# pyproject.toml
[build-system]
# XXX: If your project needs other packages to build properly, add them to this list.
requires = ["setuptools >= 42.0.0", 'numpy','scipy','astropy','matplotlib','pymc','pytensor','pyproffit','numpyro','corner']
build-backend = "setuptools.build_meta"